const categories = [
  {
    id: "mental-health",
    name: "Mental Health",
    nameNl: "Mentale Gezondheid",
    description: "Support for mental health issues, depression, anxiety, and emotional wellbeing",
    descriptionNl: "Ondersteuning bij mentale problemen, depressie, angst en emotioneel welzijn",
    icon: "brain",
    slug: "mental-health",
  },
  {
    id: "abuse-violence",
    name: "Abuse & Violence",
    nameNl: "Misbruik & Geweld",
    description: "Help for victims of abuse, violence, and assault",
    descriptionNl: "Hulp voor slachtoffers van misbruik, geweld en aanranding",
    icon: "shield",
    slug: "abuse-violence",
  },
  {
    id: "addiction",
    name: "Addiction",
    nameNl: "Verslaving",
    description: "Support for addiction to alcohol, drugs, gambling, and other substances",
    descriptionNl: "Ondersteuning bij verslaving aan alcohol, drugs, gokken en andere middelen",
    icon: "pill",
    slug: "addiction",
  },
  {
    id: "youth",
    name: "Youth & Children",
    nameNl: "Jeugd & Kinderen",
    description: "Support specifically for young people and children",
    descriptionNl: "Ondersteuning speciaal voor jongeren en kinderen",
    icon: "baby",
    slug: "youth",
  },
  {
    id: "lgbtq",
    name: "LHBTQ+",
    nameNl: "LHBTQ+",
    description: "Support for LHBTQ+ individuals and their families",
    descriptionNl: "Ondersteuning voor LHBTQ+ personen en hun families",
    icon: "heart",
    slug: "lgbtq",
  },
  {
    id: "domestic",
    name: "Domestic Issues",
    nameNl: "Huiselijke Problemen",
    description: "Help with domestic violence and family issues",
    descriptionNl: "Hulp bij huiselijk geweld en familiezaken",
    icon: "home",
    slug: "domestic",
  },
  {
    id: "financial",
    name: "Financial Help",
    nameNl: "Financiële Hulp",
    description: "Support for debt, poverty, and financial problems",
    descriptionNl: "Ondersteuning bij schulden, armoede en financiële problemen",
    icon: "wallet",
    slug: "financial",
  },
  {
    id: "legal",
    name: "Legal Aid",
    nameNl: "Juridische Hulp",
    description: "Free legal advice and support",
    descriptionNl: "Gratis juridisch advies en ondersteuning",
    icon: "scale",
    slug: "legal",
  },
];

const helplines = [
  {
    id: "113-suicide",
    name: "113 Zelfmoordpreventie",
    description: "Suicide prevention hotline available 24/7",
    descriptionNl: "Zelfmoordpreventielijn, 24 uur per dag, 7 dagen per week bereikbaar",
    phone: "113",
    website: "https://www.113.nl",
    categoryId: "mental-health",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands", "Engels"],
    isEmergency: true,
    isFeatured: true,
  },
  {
    id: "0800-0113",
    name: "113 Gratis Nummer",
    description: "Free suicide prevention hotline",
    descriptionNl: "Gratis zelfmoordpreventielijn",
    phone: "0800-0113",
    website: "https://www.113.nl",
    categoryId: "mental-health",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: true,
    isFeatured: true,
  },
  {
    id: "sensoor",
    name: "Sensoor",
    description: "Anonymous listening service for loneliness and difficult moments",
    descriptionNl: "Anonieme luisterlijn voor eenzaamheid en moeilijke momenten",
    phone: "088-0767000",
    website: "https://www.sensoor.nl",
    categoryId: "mental-health",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isFeatured: true,
  },
  {
    id: "korrelatie",
    name: "Korrelatie",
    description: "Support for psychological and social problems",
    descriptionNl: "Ondersteuning bij psychische en sociale problemen",
    phone: "0900-1450",
    website: "https://www.korrelatie.nl",
    categoryId: "mental-health",
    hoursNl: "Ma-Vr 9:00-18:00",
    languages: ["Nederlands"],
    isFeatured: true,
  },
  {
    id: "mind-korrelatie",
    name: "MIND Korrelatie",
    description: "Mental health support and information",
    descriptionNl: "Ondersteuning en informatie over mentale gezondheid",
    phone: "0900-1450",
    website: "https://www.mindkorrelatie.nl",
    categoryId: "mental-health",
    hoursNl: "Ma-Vr 9:00-21:00",
    languages: ["Nederlands"],
  },
  {
    id: "veilig-thuis",
    name: "Veilig Thuis",
    description: "Advice and support for domestic violence and child abuse",
    descriptionNl: "Advies en ondersteuning bij huiselijk geweld en kindermishandeling",
    phone: "0800-2000",
    website: "https://www.veiligthuis.nl",
    categoryId: "abuse-violence",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: true,
    isFeatured: true,
  },
  {
    id: "slachtofferhulp",
    name: "Slachtofferhulp Nederland",
    description: "Support for victims of crimes, accidents, and disasters",
    descriptionNl: "Ondersteuning voor slachtoffers van misdrijven, ongelukken en rampen",
    phone: "0900-0101",
    website: "https://www.slachtofferhulp.nl",
    categoryId: "abuse-violence",
    hoursNl: "Ma-Vr 8:00-20:00, Za 9:00-17:00",
    languages: ["Nederlands", "Engels"],
  },
  {
    id: "centrum-seksueel-geweld",
    name: "Centrum Seksueel Geweld",
    description: "24/7 support for victims of sexual violence",
    descriptionNl: "24/7 ondersteuning voor slachtoffers van seksueel geweld",
    phone: "0800-0188",
    website: "https://www.centrumseksueelgeweld.nl",
    categoryId: "abuse-violence",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: true,
  },
  {
    id: "fier",
    name: "Fier",
    description: "Expert center for violence in dependency relationships",
    descriptionNl: "Expertisecentrum voor geweld in afhankelijkheidsrelaties",
    phone: "088-2084000",
    website: "https://www.fier.nl",
    categoryId: "abuse-violence",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
  },
  {
    id: "drugsinfo",
    name: "Drugsinfo",
    description: "Information and support about drugs and addiction",
    descriptionNl: "Informatie en ondersteuning over drugs en verslaving",
    phone: "0900-1995",
    website: "https://www.drugsinfo.nl",
    categoryId: "addiction",
    hoursNl: "Ma-Vr 10:00-16:00",
    languages: ["Nederlands"],
  },
  {
    id: "anonieme-alcoholisten",
    name: "Anonieme Alcoholisten",
    description: "Support group for people with alcohol problems",
    descriptionNl: "Steungroep voor mensen met alcoholproblemen",
    phone: "020-6257877",
    website: "https://www.aa-nederland.nl",
    categoryId: "addiction",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
  },
  {
    id: "agog",
    name: "AGOG - Gokken",
    description: "Support for gambling addiction",
    descriptionNl: "Ondersteuning bij gokverslaving",
    phone: "0900-2177721",
    website: "https://www.agog.nl",
    categoryId: "addiction",
    hoursNl: "Ma-Vr 9:00-17:00",
    languages: ["Nederlands"],
  },
  {
    id: "loket-kansspel",
    name: "Loket Kansspel",
    description: "Information and help with gambling problems",
    descriptionNl: "Informatie en hulp bij gokproblemen",
    phone: "0900-2029940",
    website: "https://www.loketkansspel.nl",
    categoryId: "addiction",
    hoursNl: "Ma-Vr 9:00-21:00",
    languages: ["Nederlands"],
  },
  {
    id: "kindertelefoon",
    name: "De Kindertelefoon",
    description: "Free and anonymous helpline for children up to 18 years",
    descriptionNl: "Gratis en anonieme hulplijn voor kinderen tot 18 jaar",
    phone: "0800-0432",
    website: "https://www.kindertelefoon.nl",
    categoryId: "youth",
    hoursNl: "Dagelijks 11:00-21:00",
    languages: ["Nederlands"],
    isFeatured: true,
  },
  {
    id: "jongerenlijn",
    name: "De Jongerenlijn",
    description: "Support for young people aged 16-25",
    descriptionNl: "Ondersteuning voor jongeren van 16-25 jaar",
    phone: "0800-2000",
    website: "https://www.dejongerenlijn.nl",
    categoryId: "youth",
    hoursNl: "Dagelijks bereikbaar",
    languages: ["Nederlands"],
  },
  {
    id: "113-jongeren",
    name: "113 Jongeren",
    description: "Suicide prevention specifically for young people",
    descriptionNl: "Zelfmoordpreventie speciaal voor jongeren",
    phone: "113",
    website: "https://www.113.nl/ik-denk-aan-zelfmoord/hulp-voor-jongeren",
    categoryId: "youth",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: true,
  },
  {
    id: "coc-nederland",
    name: "COC Nederland",
    description: "LHBTQ+ rights organization with support services",
    descriptionNl: "LHBTQ+ belangenorganisatie met ondersteuningsdiensten",
    phone: "020-6234596",
    website: "https://www.coc.nl",
    categoryId: "lgbtq",
    hoursNl: "Ma-Vr 9:00-17:00",
    languages: ["Nederlands", "Engels"],
  },
  {
    id: "switchboard",
    name: "Switchboard",
    description: "Information and support for LHBTQ+ individuals",
    descriptionNl: "Informatie en ondersteuning voor LHBTQ+ personen",
    phone: "020-6232510",
    website: "https://www.switchboard.nl",
    categoryId: "lgbtq",
    hoursNl: "Ma-Vr 10:00-22:00",
    languages: ["Nederlands", "Engels"],
  },
  {
    id: "transgender-netwerk",
    name: "Transgender Netwerk Nederland",
    description: "Support and information for transgender people",
    descriptionNl: "Ondersteuning en informatie voor transgender personen",
    website: "https://www.transgendernetwerk.nl",
    categoryId: "lgbtq",
    hoursNl: "Via website",
    languages: ["Nederlands"],
  },
  {
    id: "veilig-thuis-huiselijk",
    name: "Veilig Thuis - Huiselijk Geweld",
    description: "Support for domestic violence situations",
    descriptionNl: "Ondersteuning bij huiselijk geweld situaties",
    phone: "0800-2000",
    website: "https://www.veiligthuis.nl",
    categoryId: "domestic",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
    isEmergency: true,
  },
  {
    id: "blijf-groep",
    name: "Blijf Groep",
    description: "Emergency shelter and support for domestic violence",
    descriptionNl: "Opvang en ondersteuning bij huiselijk geweld",
    phone: "0900-2015550",
    website: "https://www.blijfgroep.nl",
    categoryId: "domestic",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
  },
  {
    id: "fiom",
    name: "Fiom",
    description: "Support for unplanned pregnancy and adoption",
    descriptionNl: "Ondersteuning bij ongewenste zwangerschap en adoptie",
    phone: "088-1264646",
    website: "https://www.fiom.nl",
    categoryId: "domestic",
    hoursNl: "Ma-Vr 9:00-17:00",
    languages: ["Nederlands"],
  },
  {
    id: "nibud",
    name: "Nibud",
    description: "Financial advice and budgeting support",
    descriptionNl: "Financieel advies en budgetondersteuning",
    website: "https://www.nibud.nl",
    categoryId: "financial",
    hoursNl: "Via website",
    languages: ["Nederlands"],
  },
  {
    id: "schuldhulplijn",
    name: "Schuldhulplijn",
    description: "Free advice for debt problems",
    descriptionNl: "Gratis advies bij schulden problemen",
    phone: "0800-8115",
    website: "https://www.nvvk.nl",
    categoryId: "financial",
    hoursNl: "Ma-Vr 9:00-17:00",
    languages: ["Nederlands"],
  },
  {
    id: "geldfit",
    name: "Geldfit",
    description: "Test and get help with financial problems",
    descriptionNl: "Test en krijg hulp bij financiële problemen",
    phone: "0800-8115",
    website: "https://www.geldfit.nl",
    categoryId: "financial",
    hoursNl: "Ma-Vr 9:00-21:00",
    languages: ["Nederlands"],
  },
  {
    id: "juridisch-loket",
    name: "Het Juridisch Loket",
    description: "Free legal advice and information",
    descriptionNl: "Gratis juridisch advies en informatie",
    phone: "0900-8020",
    website: "https://www.juridischloket.nl",
    categoryId: "legal",
    hoursNl: "Ma-Vr 9:00-17:00",
    languages: ["Nederlands"],
  },
  {
    id: "advocaat-piket",
    name: "Nederlandse orde van advocaten",
    description: "search for a lawyer",
    descriptionNl: "zoek een advocaat",
    website: "https://www.advocatenorde.nl",
    categoryId: "legal",
    hoursNl: "24/7 bereikbaar",
    languages: ["Nederlands"],
  },
];

const iconSVGs = {
  brain: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z"/><path d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z"/><path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4"/><path d="M17.599 6.5a3 3 0 0 0 .399-1.375"/><path d="M6.003 5.125A3 3 0 0 0 6.401 6.5"/><path d="M3.477 10.896a4 4 0 0 1 .585-.396"/><path d="M19.938 10.5a4 4 0 0 1 .585.396"/><path d="M6 18a4 4 0 0 1-1.967-.516"/><path d="M19.967 17.484A4 4 0 0 1 18 18"/></svg>`,
  shield: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>`,
  pill: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m10.5 20.5 10-10a4.95 4.95 0 1 0-7-7l-10 10a4.95 4.95 0 1 0 7 7Z"/><path d="m8.5 8.5 7 7"/></svg>`,
  baby: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 12h.01M15 12h.01M10 16c.5.3 1.2.5 2 .5s1.5-.2 2-.5"/><path d="M19 6.3a9 9 0 0 1 1.8 3.9 2 2 0 0 1 0 3.6 9 9 0 0 1-17.6 0 2 2 0 0 1 0-3.6A9 9 0 0 1 12 3c2 0 3.5 1.1 3.5 2.5s-.9 2.5-2 2.5c-.8 0-1.5-.4-1.5-1"/></svg>`,
  heart: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>`,
  home: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9,22 9,12 15,12 15,22"></polyline></svg>`,
  wallet: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12V7H5a2 2 0 0 1 0-4h14v4"/><path d="M3 5v14a2 2 0 0 0 2 2h16v-5"/><path d="M18 12a2 2 0 0 0 0 4h4v-4Z"/></svg>`,
  scale: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/><path d="m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/><path d="M7 21h10"/><path d="M12 3v18"/><path d="M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2"/></svg>`,
  help: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"></circle><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path><path d="M12 17h.01"></path></svg>`,
};
